local SERVER_GLOBAL_IDENTIFICATION = {}

function SERVER_GLOBAL_IDENTIFICATION.parse(buffer)
	SERVER_GLOBAL_IDENTIFICATION.STRING_LENGTH = buffer(6,2)
	SERVER_GLOBAL_IDENTIFICATION.ServiceName = buffer(8, SERVER_GLOBAL_IDENTIFICATION.STRING_LENGTH:le_uint())
	SERVER_GLOBAL_IDENTIFICATION.ServiceType = buffer(8 + SERVER_GLOBAL_IDENTIFICATION.STRING_LENGTH:le_uint(), 1)
end

return SERVER_GLOBAL_IDENTIFICATION