local SERVER_GLOBAL_IDENTIFICATION = {}

function SERVER_GLOBAL_IDENTIFICATION.parse(buffer, offset)
	SERVER_GLOBAL_IDENTIFICATION.STRING_LENGTH = buffer(offset + 6,2)
	SERVER_GLOBAL_IDENTIFICATION.ServiceName = buffer(offset + 8, SERVER_GLOBAL_IDENTIFICATION.STRING_LENGTH:le_uint())
	SERVER_GLOBAL_IDENTIFICATION.ServiceType = buffer(offset + 8 + SERVER_GLOBAL_IDENTIFICATION.STRING_LENGTH:le_uint(), 1)
end

return SERVER_GLOBAL_IDENTIFICATION